<a href="https://colab.research.google.com/github/ManpreetRoy/MCANE-394E394F_PCA1/blob/main/MCAN_394F_PCA1_set3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Data Science Lab - SET 3
# MCAN-E394F


Q1. NumPy Square Matrix
Create the following NumPy matrix:
[4 7
 2 6]

Write a program to:
1. Find the determinant.
2. Find the inverse.
3. Find the transpose.
4. Calculate the sum of all elements.
5. Display its shape and dimensions.

In [1]:
import numpy as np

#crate the Numpy matrix
A = np.array([[4, 7],
              [2, 6]])

print("Matrix:")
print(A)

# 1. Find determinant
det = np.linalg.det(A)
print("\nDeterminant:", det)

# 2. Find inverse
inverse = np.linalg.inv(A)
print("\nInverse:")
print(inverse)

# 3. Find transpose
transpose = A.T
print("\nTranspose:")
print(transpose)

# 4. Sum of all elements
total_sum = np.sum(A)
print("\nSum of all elements:", total_sum)

# 5. Display shape and dimensions
print("\nShape:", A.shape)
print("Dimensions:", A.ndim)

Matrix:
[[4 7]
 [2 6]]

Determinant: 10.000000000000002

Inverse:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Transpose:
[[4 2]
 [7 6]]

Sum of all elements: 19

Shape: (2, 2)
Dimensions: 2


Q2. NumPy Reshaping
Create a NumPy array containing numbers from 1 to 12.

Perform:
1. Display the original array.
2. Reshape it into a 3x4 matrix.
3. Reshape it into a 2x6 matrix.
4. Display the first row.
5. Display the last column.
6. Calculate the sum of each row.

In [2]:
import numpy as np

# Create NumPy array containing numbers from 1 to 12
arr = np.arange(1, 13)

# 1. Display the original array
print("Original Array:")
print(arr)

# 2. Reshape into 3x4 matrix
matrix_3x4 = arr.reshape(3, 4)
print("\n3x4 Matrix:")
print(matrix_3x4)

# 3. Reshape into 2x6 matrix
matrix_2x6 = arr.reshape(2, 6)
print("\n2x6 Matrix:")
print(matrix_2x6)

# 4. Display the first row
print("\nFirst Row:")
print(matrix_3x4[0])

# 5. Display the last column
print("\nLast Column:")
print(matrix_3x4[:, -1])

# 6. Calculate the sum of each row
print("\nSum of Each Row:")
print(np.sum(matrix_3x4, axis=1))

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

3x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2x6 Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

First Row:
[1 2 3 4]

Last Column:
[ 4  8 12]

Sum of Each Row:
[10 26 42]


Q3. Temperature Dictionary
Create the following dictionary:
temperature = {
  "Monday": 31,
  "Tuesday": 33,
  "Wednesday": 30,
  "Thursday": 35,
  "Friday": 32,
  "Saturday": 36,
  "Sunday": 34
}

Find:
1. Maximum temperature
2. Minimum temperature
3. Average temperature
4. Day with the highest temperature
5. Days having temperature above 33

Q4. Dictionary Comprehension
Create a dictionary containing marks of six students.

Using dictionary comprehension, create a new dictionary containing only
students who scored 80 or above.

Also:
1. Display the original dictionary.
2. Display the filtered dictionary.
3. Count the number of selected students.

Q5. Subject-wise Marks Analysis Using Dictionary
Create the following dictionary containing marks of five students:
marks = {
  "Amit": {"Python": 78, "DBMS": 82, "Maths": 75},
  "Riya": {"Python": 91, "DBMS": 88, "Maths": 94},
  "Rahul": {"Python": 65, "DBMS": 70, "Maths": 68},
  "Sneha": {"Python": 84, "DBMS": 79, "Maths": 88},
  "Arjun": {"Python": 73, "DBMS": 76, "Maths": 80}
}

Write a Python program to:
1. Display the complete dictionary.
2. Calculate the average marks in Python.
3. Calculate the average marks in DBMS.
4. Calculate the average marks in Maths.
5. Find the subject having the highest average marks.